name: Bento package

on: [push, pull_request]

jobs:
  package:
    name: "Package using Bento"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Bento
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/greeeen-dev/zenbento.py.git
      - name: Install zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
      - name: Package
        run: |
          python -m zenbento package
          cd .zenbento
          zip -r ../package.zip package
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "package.zip"
